pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - approved-reviews-by>=1
      - check-success=GitGuardian Security Checks
    actions:
      merge:
        method: squash
        
  - name: Automerge translations
    conditions:
      - author=HypixelTranslators
      - check-success=GitGuardian Security Checks
    actions:
      merge:
        method: squash
