pull_request_rules:
    - name: Automerge translations
      conditions:
          - author=HypixelTranslators
          - check-success=GitGuardian Security Checks
          - check-success=Compile and lint
      actions:
          merge:
              method: squash
