# commit_message: Crowdin - New translations for %original_file_name% (%language%)
# append_commit_message: false
files:
  - source: /strings/en/*.json
    translation: /strings/%osx_locale%/%original_file_name%
    update_option: update_as_unapproved
