name: Feature request
description: Suggest an idea for this project
labels: 'Suggestion'
assignees: ImRodry
body:
  - type: markdown
    attributes:
      value: |
        Test the bot at https://discord.gg/rcT948A
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: |
        Describe the feature you're suggesting with as much detail as possible, as well as how you think it should work.
        If you're experienced with the language the bot is coded in, feel free to also go add technical details about your request.
        If you're suggesting an improvement to an already existing feature, feel free to mention that.
        
        Tip: You can attach images or log files by clicking this area and then dragging files into it.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: |
        Describe other alternatives you've considered to the feature you're suggesting, if any.
        Make sure to include as much detail as you did in the previous field.
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: |
        Add any other information about your suggestion here.
        You can also make mockups of your idea and upload screenshots/links to those in here.
