name: Build docker image
on:
    push:
        branches:
            - "main"
    pull_request:

jobs:
    build:
        name: Build docker image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v3
            - name: Build docker image
              run: docker build . --file Dockerfile --tag hypixel-translators-bot:$(date +%s)
